actors:
  北畠一翔:
    image_url:
    name: 北畠一翔
    url: https://www.kitabatake1013.jp/
author: 北畠一翔
description: 視覚障害者向けテクノロジーポッドキャスト
description_long: 全盲のパーソナリティー・北畠一翔が、視覚障害関連のテクノロジーについてお届けするポッドキャストです。見えなくても使える便利なソフトウェアや機器のデモンストレーション、視覚障害者の間で話題になっている最新ニュースなど、日々の生活や情報収集に役立つさまざまなテーマを取り上げていきます。
email: podcast@kitabatake1013.jp
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag:
itunes_podcast_url:
keywords:
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Blind Tech JP
url: https://podcast.kitabatake1013.jp
